RUN cd /etc/apk/keys && /
    wget http://alpine.adiscon.com/rsyslog@lists.adiscon.com-5a55e598.rsa.pub && / 
    echo 'http://alpine.adiscon.com/3.7/stable' >> /etc/apk/repositories && /
    apk update && /
    apk add rsyslog && /
	apk add openrc --no-cache && /
    rc-status && /
	cd / && /
	touch /run/openrc/softlevel && /
    rc-service rsyslog start
